vich_uploader:
    db_driver: orm

    mappings:
        servant_image:
            uri_prefix: /images/servant
            upload_destination: '%kernel.project_dir%/public/images/servant'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
