#   index:
#    path: /
#    controller: App\Controller\DefaultController::index

#home : 
    #path: /
    #controller: App\Controller\HomeController::index

home : 
    path: /
    controller: App\Controller\HomeController::index
servant.index : 
    path: /servant.index
    controller: App\Controller\ServantController::index

servant.show :
    path: /servants/{id}
    controller: App\Controller\ServantController::show

admin.servant.index : 
    path: /admin/servant
    controller: App\Controller\admin\AdminServantController::index

admin.servant.new :
    path: /admin/servant/create
    controller: App\Controller\admin\AdminServantController::new
    
admin.servant.edit :
    path: /admin/servant/{id}
    controller: App\Controller\admin\AdminServantController::edit

logout :
    path: /logout
